name: branch

on:
  push:
    branches-ignore:
      - master
      - 'docs'

jobs:
  stack-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: stack build
    - run: stack test
